# Generated by Django 5.2.1 on 2025-05-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10000)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('HOUSING', 'Housing'), ('TRANSPORT', 'Transport'), ('FOOD', 'Food'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('FINANCIAL', 'Financial')], max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
