# Generated by Django 5.2.1 on 2025-05-29 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='description',
            new_name='expense',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='amount',
            new_name='value',
        ),
    ]
